<?php
//---------------------------------------------------------------------------
// OpenID Module
// Author: Nat Sakimura
// License: GPL
//---------------------------------------------------------------------------

$modversion['name'] = _MI_OPENID_NAME;
$modversion['version'] = 0.22;
$modversion['description'] = _MI_OPENID_DESC;
$modversion['credits'] = "Nat Sakimura<br />( http://www.sakimura.org/ )<br />";
$modversion['help'] = "openid.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/openid_slogo.png";
$modversion['dirname'] = "openid";

// Admin things
$modversion['hasAdmin'] = 1;
//$modversion['adminindex'] = "admin/index.php";
//$modversion['adminmenu'] = "admin/menu.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "openid_localid";

// Blocks
$modversion['blocks'][1]['file'] = "openidurl.php";
$modversion['blocks'][1]['name'] = _MI_OPENID_BNAME1;
$modversion['blocks'][1]['description'] = "Shows OpenID Login box";
$modversion['blocks'][1]['show_func'] = "openid_login_show";
$modversion['blocks'][1]['template'] = 'openidurl.html';

// Menu
$modversion['hasMain'] = 1;

// Search
$modversion['hasSearch'] = 0;

// Comments
$modversion['hasComments'] = 0;

// Templates
$modversion['templates'][1]['file'] = 'openid_consumer.html';
$modversion['templates'][1]['description'] = 'OpenID Consumer Screen';
$modversion['templates'][2]['file'] = 'openid_new_user.html';
$modversion['templates'][2]['description'] = 'New OpenID User Dialog';
$modversion['templates'][3]['file'] = 'openid_generic.html';
$modversion['templates'][3]['description'] = 'Generic Screen';

?>
